FROM centurylink/mysql
MAINTAINER docker@unxs.io

ENV MYSQL_ROOT_PASSWORD doesnotmatter
ENV MYSQL_DATABASE idns
ENV MYSQL_USER idns
ENV MYSQL_PASSWORD wsxedc

#useful commands:
#docker build -t local/unxsbind-mysql .

#docker rm -f unxsbind-mysql;docker run --restart unless-stopped --name unxsbind-mysql --volume /var/lib/mysql:/var/lib/mysql -p 3306:3306 -d local/unxsbind-mysql

