// svn ID removed
// English: USA
// Navigation bar buttons and results

#define LANG_NB_LIST "List"
#define LANG_NB_MODIFY "Modify"
#define LANG_NB_CONFIRMMOD "Confirm Modify"
#define LANG_NB_NEW "New"
#define LANG_NB_DELETE "Delete"
#define LANG_NB_CONFIRMNEW "Create New Record"
#define LANG_NBB_CONFIRMNEW "<input class=lrevButton title='Double check!' type=submit name=gcCommand value='Create New Record'>"
#define LANG_NB_CONFIRMDEL "Confirm Delete"
#define LANG_NBB_CONFIRMDEL "<input class=lwarnButton title='No undo available!' type=submit name=gcCommand value='Confirm Delete'>"
#define LANG_NBB_CONFIRMMOD "<input class=lalertButton title='Double check!' type=submit name=gcCommand value='Confirm Modify'>"


#define LANG_NBR_FOUND " Found"
#define LANG_NBR_MODIFIED " Modified"
#define LANG_NBR_NEW " New"
#define LANG_NBR_NORECS " No records found"
#define LANG_NBRF_SHOWING " (Showing %lu of %d)"

#define LANG_NBR_RECEXISTS "<blink>Record already exists"
#define LANG_NBR_NEWRECADDED "New record %u added"
#define LANG_NBR_RECDELETED "Record Deleted"
#define LANG_NBR_RECNOTDELETED "Record Not Deleted"
#define LANG_NBR_RECNOTEXIST "<blink>Record does not exist"
#define LANG_NBR_MULTRECS "<blink>Multiple rows!"
#define LANG_NBR_EXTMOD "<blink>This record was just modified by another user!"
#define LANG_NBRF_REC_MODIFIED "record %s modified"

#define LANG_NBB_SKIPFIRST "<input class=first title='Skip to first record' type=submit name=gcFind value='<<' >"
#define LANG_NBB_SKIPBACK "<input class=back title='Go back one record' type=submit name=gcFind value='< ' >"
#define LANG_NBB_SKIPNEXT "<input class=next title='Advance to next record' type=submit name=gcFind value=' >' >"
#define LANG_NBB_SKIPLAST "<input class=last title='Skip to last record' type=submit name=gcFind value='>>' >\n"

#define LANG_NBB_NEWREV "<input class=revButton title='Create new record' type=submit name=gcCommand value=New>"
#define LANG_NBB_NEW "<input class=new title='Create new record' type=submit name=gcCommand value=New>"
#define LANG_NBB_DELETE "<input class=delete title='Delete current record' type=submit name=gcCommand value=Delete>"
#define LANG_NBB_MODIFY "<input class=modify title='Modify current record' type=submit name=gcCommand value=Modify>"

#define LANG_NBB_LIST "<input class=list title='Paginated listing of all records' type=submit name=gcFind value=List>"
#define LANG_NBB_SEARCH "<input class=refresh title='Find record with parameters set below' type=submit name=gcFind value=Search>"

#define LANG_PAGEMACHINE_HINT "No matching records found.<br>"
#define LANG_PAGEMACHINE_SHOWING "Page %d/%d (Records %d-%d of %d)\n"
#define LANG_PAGEMACHINE_SEARCH "<input type=submit name=gcFind value=Search >"
#define LANG_PAGEMACHINE_SEARCHBUTTON "Search"

//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tNSType
#define LANG_FL_tNSType_uNSType "uNSType"
#define LANG_FT_tNSType_uNSType "Primary Key"
#define LANG_FL_tNSType_cLabel "cLabel"
#define LANG_FT_tNSType_cLabel "Short label"
#define LANG_FL_tNSType_uOwner "uOwner"
#define LANG_FT_tNSType_uOwner "Record owner"
#define LANG_FL_tNSType_uCreatedBy "uCreatedBy"
#define LANG_FT_tNSType_uCreatedBy "uClient for last insert"
#define LANG_FL_tNSType_uCreatedDate "uCreatedDate"
#define LANG_FT_tNSType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tNSType_uModBy "uModBy"
#define LANG_FT_tNSType_uModBy "uClient for last update"
#define LANG_FL_tNSType_uModDate "uModDate"
#define LANG_FT_tNSType_uModDate "Unix seconds date last update"
//tNSSet
#define LANG_FL_tNSSet_uNSSet "uNSSet"
#define LANG_FT_tNSSet_uNSSet "Primary Key"
#define LANG_FL_tNSSet_cLabel "cLabel"
#define LANG_FT_tNSSet_cLabel "Short label"
#define LANG_FL_tNSSet_cMasterIPs "Master IPs"
#define LANG_FT_tNSSet_cMasterIPs "Semi-colon list of IPs"
#define LANG_FL_tNSSet_uOwner "uOwner"
#define LANG_FT_tNSSet_uOwner "Record owner"
#define LANG_FL_tNSSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tNSSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tNSSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tNSSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tNSSet_uModBy "uModBy"
#define LANG_FT_tNSSet_uModBy "uClient for last update"
#define LANG_FL_tNSSet_uModDate "uModDate"
#define LANG_FT_tNSSet_uModDate "Unix seconds date last update"
//tNS
#define LANG_FL_tNS_uNS "uNS"
#define LANG_FT_tNS_uNS "Primary Key"
#define LANG_FL_tNS_cFQDN "cFQDN"
#define LANG_FT_tNS_cFQDN "FQDN of a NS"
#define LANG_FL_tNS_uNSType "uNSType"
#define LANG_FT_tNS_uNSType "Key into tNSType"
#define LANG_FL_tNS_uNSSet "uNSSet"
#define LANG_FT_tNS_uNSSet "Key into tNSSet"
#define LANG_FL_tNS_uServer "uServer"
#define LANG_FT_tNS_uServer "Key into tServer"
#define LANG_FL_tNS_uOwner "uOwner"
#define LANG_FT_tNS_uOwner "Record owner"
#define LANG_FL_tNS_uCreatedBy "uCreatedBy"
#define LANG_FT_tNS_uCreatedBy "uClient for last insert"
#define LANG_FL_tNS_uCreatedDate "uCreatedDate"
#define LANG_FT_tNS_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tNS_uModBy "uModBy"
#define LANG_FT_tNS_uModBy "uClient for last update"
#define LANG_FL_tNS_uModDate "uModDate"
#define LANG_FT_tNS_uModDate "Unix seconds date last update"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_uServer "uServer"
#define LANG_FT_tConfiguration_uServer "uServer"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
//tAuthorize
#define LANG_FL_tAuthorize_uAuthorize "uAuthorize"
#define LANG_FT_tAuthorize_uAuthorize "Primary Key"
#define LANG_FL_tAuthorize_cLabel "cLabel"
#define LANG_FT_tAuthorize_cLabel "Short label"
#define LANG_FL_tAuthorize_cIpMask "cIpMask"
#define LANG_FT_tAuthorize_cIpMask "Allow user from this IP"
#define LANG_FL_tAuthorize_uPerm "uPerm"
#define LANG_FT_tAuthorize_uPerm "User permission level"
#define LANG_FL_tAuthorize_uCertClient "uCertClient"
#define LANG_FT_tAuthorize_uCertClient "User uClient"
#define LANG_FL_tAuthorize_cPasswd "cPasswd"
#define LANG_FT_tAuthorize_cPasswd "Encrypted cgi login password"
#define LANG_FL_tAuthorize_cClrPasswd "cClrPasswd"
#define LANG_FT_tAuthorize_cClrPasswd "Optionally used non encrypted login password"
#define LANG_FL_tAuthorize_uOwner "uOwner"
#define LANG_FT_tAuthorize_uOwner "Record owner"
#define LANG_FL_tAuthorize_uCreatedBy "uCreatedBy"
#define LANG_FT_tAuthorize_uCreatedBy "uClient for last insert"
#define LANG_FL_tAuthorize_uCreatedDate "uCreatedDate"
#define LANG_FT_tAuthorize_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tAuthorize_uModBy "uModBy"
#define LANG_FT_tAuthorize_uModBy "uClient for last update"
#define LANG_FL_tAuthorize_uModDate "uModDate"
#define LANG_FT_tAuthorize_uModDate "Unix seconds date last update"
//tMonth
#define LANG_FL_tMonth_uMonth "uMonth"
#define LANG_FT_tMonth_uMonth "Primary Key"
#define LANG_FL_tMonth_cLabel "cLabel"
#define LANG_FT_tMonth_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonth_uOwner "uOwner"
#define LANG_FT_tMonth_uOwner "Record owner"
#define LANG_FL_tMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonth_uModBy "uModBy"
#define LANG_FT_tMonth_uModBy "uClient for last update"
#define LANG_FL_tMonth_uModDate "uModDate"
#define LANG_FT_tMonth_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlossary "uGlossary"
#define LANG_FT_tGlossary_uGlossary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tGroupType
#define LANG_FL_tGroupType_uGroupType "uGroupType"
#define LANG_FT_tGroupType_uGroupType "Primary Key"
#define LANG_FL_tGroupType_cLabel "cLabel"
#define LANG_FT_tGroupType_cLabel "Short label"
#define LANG_FL_tGroupType_uOwner "uOwner"
#define LANG_FT_tGroupType_uOwner "Record owner"
#define LANG_FL_tGroupType_uCreatedBy "uCreatedBy"
#define LANG_FT_tGroupType_uCreatedBy "uClient for last insert"
#define LANG_FL_tGroupType_uCreatedDate "uCreatedDate"
#define LANG_FT_tGroupType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGroupType_uModBy "uModBy"
#define LANG_FT_tGroupType_uModBy "uClient for last update"
#define LANG_FL_tGroupType_uModDate "uModDate"
#define LANG_FT_tGroupType_uModDate "Unix seconds date last update"
//tGroup
#define LANG_FL_tGroup_uGroup "uGroup"
#define LANG_FT_tGroup_uGroup "Primary Key"
#define LANG_FL_tGroup_cLabel "cLabel"
#define LANG_FT_tGroup_cLabel "Short label"
#define LANG_FL_tGroup_uGroupType "uGroupType"
#define LANG_FT_tGroup_uGroupType "Group type association"
#define LANG_FL_tGroup_uOwner "uOwner"
#define LANG_FT_tGroup_uOwner "Record owner"
#define LANG_FL_tGroup_uCreatedBy "uCreatedBy"
#define LANG_FT_tGroup_uCreatedBy "uClient for last insert"
#define LANG_FL_tGroup_uCreatedDate "uCreatedDate"
#define LANG_FT_tGroup_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGroup_uModBy "uModBy"
#define LANG_FT_tGroup_uModBy "uClient for last update"
#define LANG_FL_tGroup_uModDate "uModDate"
#define LANG_FT_tGroup_uModDate "Unix seconds date last update"
//tGroupGlue
#define LANG_FL_tGroupGlue_uGroupGlue "uGroupGlue"
#define LANG_FT_tGroupGlue_uGroupGlue "Primary Key"
#define LANG_FL_tGroupGlue_uGroup "uGroup"
#define LANG_FT_tGroupGlue_uGroup "Glue into tGroup"
#define LANG_FL_tGroupGlue_uNode "uNode"
#define LANG_FT_tGroupGlue_uNode "Glue into tNode"
#define LANG_FL_tGroupGlue_uContainer "uContainer"
#define LANG_FT_tGroupGlue_uContainer "Glue into tContainer"
//tServer
#define LANG_FL_tServer_uServer "uServer"
#define LANG_FT_tServer_uServer "Primary Key"
#define LANG_FL_tServer_cLabel "cLabel"
#define LANG_FT_tServer_cLabel "Short label"
#define LANG_FL_tServer_uOwner "uOwner"
#define LANG_FT_tServer_uOwner "Record owner"
#define LANG_FL_tServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tServer_uModBy "uModBy"
#define LANG_FT_tServer_uModBy "uClient for last update"
#define LANG_FL_tServer_uModDate "uModDate"
#define LANG_FT_tServer_uModDate "Unix seconds date last update"
//tJobStatus
#define LANG_FL_tJobStatus_uJobStatus "uJobStatus"
#define LANG_FT_tJobStatus_uJobStatus "Primary Key"
#define LANG_FL_tJobStatus_cLabel "cLabel"
#define LANG_FT_tJobStatus_cLabel "Short label"
#define LANG_FL_tJobStatus_uOwner "uOwner"
#define LANG_FT_tJobStatus_uOwner "Record owner"
#define LANG_FL_tJobStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tJobStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tJobStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tJobStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJobStatus_uModBy "uModBy"
#define LANG_FT_tJobStatus_uModBy "uClient for last update"
#define LANG_FL_tJobStatus_uModDate "uModDate"
#define LANG_FT_tJobStatus_uModDate "Unix seconds date last update"
//tStatus
#define LANG_FL_tStatus_uStatus "uStatus"
#define LANG_FT_tStatus_uStatus "Primary Key"
#define LANG_FL_tStatus_cLabel "cLabel"
#define LANG_FT_tStatus_cLabel "Short label"
#define LANG_FL_tStatus_uOwner "uOwner"
#define LANG_FT_tStatus_uOwner "Record owner"
#define LANG_FL_tStatus_uCreatedBy "uCreatedBy"
#define LANG_FT_tStatus_uCreatedBy "uClient for last insert"
#define LANG_FL_tStatus_uCreatedDate "uCreatedDate"
#define LANG_FT_tStatus_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tStatus_uModBy "uModBy"
#define LANG_FT_tStatus_uModBy "uClient for last update"
#define LANG_FL_tStatus_uModDate "uModDate"
#define LANG_FT_tStatus_uModDate "Unix seconds date last update"
//tZone
#define LANG_FL_tZone_uZone "uZone"
#define LANG_FT_tZone_uZone "Primary Key"
#define LANG_FL_tZone_cZone "cZone"
#define LANG_FT_tZone_cZone "Fully qualified zone name"
#define LANG_FL_tZone_uNSSet "uNSSet"
#define LANG_FT_tZone_uNSSet "Optional group of name servers by hardware"
#define LANG_FL_tZone_cHostmaster "cHostmaster"
#define LANG_FT_tZone_cHostmaster "eMail address of responsible person of this zone"
#define LANG_FL_tZone_uSerial "uSerial"
#define LANG_FT_tZone_uSerial "Zone serial number"
#define LANG_FL_tZone_uExpire "uExpire"
#define LANG_FT_tZone_uExpire "Slave server expiration time"
#define LANG_FL_tZone_uRefresh "uRefresh"
#define LANG_FT_tZone_uRefresh "Slave server refresh time"
#define LANG_FL_tZone_uTTL "uTTL"
#define LANG_FT_tZone_uTTL "Default time to live of resource records"
#define LANG_FL_tZone_uRetry "uRetry"
#define LANG_FT_tZone_uRetry "Slave server retry interval after uRefresh"
#define LANG_FL_tZone_uZoneTTL "uZoneTTL"
#define LANG_FT_tZone_uZoneTTL "Zone TTL seconds"
#define LANG_FL_tZone_uMailServers "uMailServers"
#define LANG_FT_tZone_uMailServers "Group of mail servers"
#define LANG_FL_tZone_uView "uView"
#define LANG_FT_tZone_uView "Optional tView Group"
#define LANG_FL_tZone_cMainAddress "cMainAddress"
#define LANG_FT_tZone_cMainAddress "Main A Record"
#define LANG_FL_tZone_uRegistrar "uRegistrar"
#define LANG_FT_tZone_uRegistrar "Registrar of Record for this Zone if Applies"
#define LANG_FL_tZone_uSecondaryOnly "uSecondaryOnly"
#define LANG_FT_tZone_uSecondaryOnly "Secondary DNS Service Only. cMasterIPs Would be External Customer Provided Master"
#define LANG_FL_tZone_cMasterIPs "cMasterIPs"
#define LANG_FT_tZone_cMasterIPs "Slave zones master IP source(s)"
#define LANG_FL_tZone_cAllowTransfer "cAllowTransfer"
#define LANG_FT_tZone_cAllowTransfer "IP address(es) that are allowed to copy the zone info from the server (master or slave)"
#define LANG_FL_tZone_cOptions "cOptions"
#define LANG_FT_tZone_cOptions "slave.zones and master.zones zone options"
#define LANG_FL_tZone_uClient "uClient"
#define LANG_FL_tZone_uOwner "uOwner"
#define LANG_FT_tZone_uOwner "Record owner"
#define LANG_FL_tZone_uCreatedBy "uCreatedBy"
#define LANG_FT_tZone_uCreatedBy "uClient for last insert"
#define LANG_FL_tZone_uCreatedDate "uCreatedDate"
#define LANG_FT_tZone_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tZone_uModBy "uModBy"
#define LANG_FT_tZone_uModBy "uClient for last update"
#define LANG_FL_tZone_uModDate "uModDate"
#define LANG_FT_tZone_uModDate "Unix seconds date last update"
#define LANG_BL_TableAddRR "Add Resource Record"
#define LANG_BT_TableAddRR "Add resource record to this zone"
//tResource
#define LANG_FL_tResource_uResource "uResource"
#define LANG_FT_tResource_uResource "Primary Key"
#define LANG_FL_tResource_uZone "uZone"
#define LANG_FT_tResource_uZone "Belongs to this tZone"
#define LANG_FL_tResource_cName "cName"
#define LANG_FT_tResource_cName "Resource name or @"
#define LANG_FL_tResource_uTTL "uTTL"
#define LANG_FT_tResource_uTTL "Resource record TTL in seconds"
#define LANG_FL_tResource_uRRType "uRRType"
#define LANG_FT_tResource_uRRType "Resource record type"
#define LANG_FL_tResource_cParam1 "cParam1"
#define LANG_FT_tResource_cParam1 "Parameter 1 of resource record"
#define LANG_FL_tResource_cParam2 "cParam2"
#define LANG_FT_tResource_cParam2 "Parameter 2 of resource record"
#define LANG_FL_tResource_cParam3 "cParam3"
#define LANG_FT_tResource_cParam3 "Parameter 3 of resource record"
#define LANG_FL_tResource_cParam4 "cParam4"
#define LANG_FT_tResource_cParam4 "Parameter 4 of resource record"
#define LANG_FL_tResource_cComment "cComment"
#define LANG_FT_tResource_cComment "Resource record comment"
#define LANG_FL_tResource_uOwner "uOwner"
#define LANG_FT_tResource_uOwner "Record owner"
#define LANG_FL_tResource_uCreatedBy "uCreatedBy"
#define LANG_FT_tResource_uCreatedBy "uClient for last insert"
#define LANG_FL_tResource_uCreatedDate "uCreatedDate"
#define LANG_FT_tResource_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tResource_uModBy "uModBy"
#define LANG_FT_tResource_uModBy "uClient for last update"
#define LANG_FL_tResource_uModDate "uModDate"
#define LANG_FT_tResource_uModDate "Unix seconds date last update"
//tRRType
#define LANG_FL_tRRType_uRRType "uRRType"
#define LANG_FT_tRRType_uRRType "Primary Key"
#define LANG_FL_tRRType_cLabel "cLabel"
#define LANG_FT_tRRType_cLabel "Short label"
#define LANG_FL_tRRType_uParam1 "uParam1"
#define LANG_FT_tRRType_uParam1 "Requires parameter 1"
#define LANG_FL_tRRType_uParam2 "uParam2"
#define LANG_FT_tRRType_uParam2 "Requires parameter 2"
#define LANG_FL_tRRType_cParam1Func "cParam1Func"
#define LANG_FT_tRRType_cParam1Func "Input validation function"
#define LANG_FL_tRRType_cParam2Func "cParam2Func"
#define LANG_FT_tRRType_cParam2Func "Input validation function"
#define LANG_FL_tRRType_cParam3Func "cParam3Func"
#define LANG_FT_tRRType_cParam3Func "Input validation function"
#define LANG_FL_tRRType_cParam4Func "cParam4Func"
#define LANG_FT_tRRType_cParam4Func "Input validation function"
#define LANG_FL_tRRType_cParam1Label "cParam1Label"
#define LANG_FT_tRRType_cParam1Label "Label for interfaces"
#define LANG_FL_tRRType_cParam2Label "cParam2Label"
#define LANG_FT_tRRType_cParam2Label "Label for interfaces"
#define LANG_FL_tRRType_cParam3Label "cParam3Label"
#define LANG_FT_tRRType_cParam3Label "Label for interfaces"
#define LANG_FL_tRRType_cParam4Label "cParam4Label"
#define LANG_FT_tRRType_cParam4Label "Label for interfaces"
#define LANG_FL_tRRType_cParam1Tip "cParam1Tip"
#define LANG_FT_tRRType_cParam1Tip "Html title tool-tip for interfaces"
#define LANG_FL_tRRType_cParam2Tip "cParam2Tip"
#define LANG_FT_tRRType_cParam2Tip "Html title tool-tip for interfaces"
#define LANG_FL_tRRType_cParam3Tip "cParam3Tip"
#define LANG_FT_tRRType_cParam3Tip "Html title tool-tip for interfaces"
#define LANG_FL_tRRType_cParam4Tip "cParam4Tip"
#define LANG_FT_tRRType_cParam4Tip "Html title tool-tip for interfaces"
#define LANG_FL_tRRType_uParam3 "uParam3"
#define LANG_FT_tRRType_uParam3 "Requires parameter 3"
#define LANG_FL_tRRType_uParam4 "uParam4"
#define LANG_FT_tRRType_uParam4 "Requires parameter 4"
#define LANG_FL_tRRType_uName "uName"
#define LANG_FT_tRRType_uName "Requires tResource.cName"
#define LANG_FL_tRRType_cNameFunc "cNameFunc"
#define LANG_FT_tRRType_cNameFunc "Input validation function"
#define LANG_FL_tRRType_cNameLabel "cNameLabel"
#define LANG_FT_tRRType_cNameLabel "Label for interfaces"
#define LANG_FL_tRRType_cNameTip "cNameTip"
#define LANG_FT_tRRType_cNameTip "Html title tool-tip for interfaces"
#define LANG_FL_tRRType_uOwner "uOwner"
#define LANG_FT_tRRType_uOwner "Record owner"
#define LANG_FL_tRRType_uCreatedBy "uCreatedBy"
#define LANG_FT_tRRType_uCreatedBy "uClient for last insert"
#define LANG_FL_tRRType_uCreatedDate "uCreatedDate"
#define LANG_FT_tRRType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tRRType_uModBy "uModBy"
#define LANG_FT_tRRType_uModBy "uClient for last update"
#define LANG_FL_tRRType_uModDate "uModDate"
#define LANG_FT_tRRType_uModDate "Unix seconds date last update"
//tJob
#define LANG_FL_tJob_uJob "uJob"
#define LANG_FT_tJob_uJob "Unique job ID"
#define LANG_FL_tJob_uMasterJob "uMasterJob"
#define LANG_FT_tJob_uMasterJob "Unique group job ID"
#define LANG_FL_tJob_cJob "cJob"
#define LANG_FT_tJob_cJob "Job command"
#define LANG_FL_tJob_cZone "cZone"
#define LANG_FT_tJob_cZone "Command argument usually a zone"
#define LANG_FL_tJob_uNSSet "uNSSet"
#define LANG_FT_tJob_uNSSet "Job assigned to these name servers"
#define LANG_FL_tJob_cTargetServer "cTargetServer"
#define LANG_FT_tJob_cTargetServer "Job assigned to this name servers"
#define LANG_FL_tJob_uPriority "uPriority"
#define LANG_FT_tJob_uPriority "Job priority"
#define LANG_FL_tJob_uTime "uTime"
#define LANG_FT_tJob_uTime "Unix date and time for job to start"
#define LANG_FL_tJob_cJobData "cJobData"
#define LANG_FT_tJob_cJobData "Aux job data"
#define LANG_FL_tJob_uOwner "uOwner"
#define LANG_FT_tJob_uOwner "Record owner"
#define LANG_FL_tJob_uCreatedBy "uCreatedBy"
#define LANG_FT_tJob_uCreatedBy "uClient for last insert"
#define LANG_FL_tJob_uCreatedDate "uCreatedDate"
#define LANG_FT_tJob_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tJob_uModBy "uModBy"
#define LANG_FT_tJob_uModBy "uClient for last update"
#define LANG_FL_tJob_uModDate "uModDate"
#define LANG_FT_tJob_uModDate "Unix seconds date last update"
//tMailServer
#define LANG_FL_tMailServer_uMailServer "uMailServer"
#define LANG_FT_tMailServer_uMailServer "Primary Key"
#define LANG_FL_tMailServer_cLabel "cLabel"
#define LANG_FT_tMailServer_cLabel "Group of mail servers"
#define LANG_FL_tMailServer_cList "cList"
#define LANG_FT_tMailServer_cList "List of mail servers"
#define LANG_FL_tMailServer_uOwner "uOwner"
#define LANG_FT_tMailServer_uOwner "Record owner"
#define LANG_FL_tMailServer_uCreatedBy "uCreatedBy"
#define LANG_FT_tMailServer_uCreatedBy "uClient for last insert"
#define LANG_FL_tMailServer_uCreatedDate "uCreatedDate"
#define LANG_FT_tMailServer_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMailServer_uModBy "uModBy"
#define LANG_FT_tMailServer_uModBy "uClient for last update"
#define LANG_FL_tMailServer_uModDate "uModDate"
#define LANG_FT_tMailServer_uModDate "Unix seconds date last update"
//tConfiguration
#define LANG_FL_tConfiguration_uConfiguration "uConfiguration"
#define LANG_FT_tConfiguration_uConfiguration "Primary Key"
#define LANG_FL_tConfiguration_cLabel "cLabel"
#define LANG_FT_tConfiguration_cLabel "cLabel is Name of Name/Value Pair"
#define LANG_FL_tConfiguration_cValue "cValue"
#define LANG_FT_tConfiguration_cValue "Value of name(cLabel)/value pair"
#define LANG_FL_tConfiguration_cComment "cComment"
#define LANG_FT_tConfiguration_cComment "Comment about this configuration name/value pair"
#define LANG_FL_tConfiguration_uOwner "uOwner"
#define LANG_FT_tConfiguration_uOwner "Record owner"
#define LANG_FL_tConfiguration_uCreatedBy "uCreatedBy"
#define LANG_FT_tConfiguration_uCreatedBy "uClient for last insert"
#define LANG_FL_tConfiguration_uCreatedDate "uCreatedDate"
#define LANG_FT_tConfiguration_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tConfiguration_uModBy "uModBy"
#define LANG_FT_tConfiguration_uModBy "uClient for last update"
#define LANG_FL_tConfiguration_uModDate "uModDate"
#define LANG_FT_tConfiguration_uModDate "Unix seconds date last update"
//tTemplate
#define LANG_FL_tTemplate_uTemplate "uTemplate"
#define LANG_FT_tTemplate_uTemplate "Primary Key"
#define LANG_FL_tTemplate_cLabel "cLabel"
#define LANG_FT_tTemplate_cLabel "Short label"
#define LANG_FL_tTemplate_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplate_uTemplateSet "Short label"
#define LANG_FL_tTemplate_uTemplateType "uTemplateType"
#define LANG_FT_tTemplate_uTemplateType "Short label"
#define LANG_FL_tTemplate_cComment "cComment"
#define LANG_FT_tTemplate_cComment "About the template"
#define LANG_FL_tTemplate_cTemplate "cTemplate"
#define LANG_FT_tTemplate_cTemplate "Template itself"
#define LANG_FL_tTemplate_uOwner "uOwner"
#define LANG_FT_tTemplate_uOwner "Record owner"
#define LANG_FL_tTemplate_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplate_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplate_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplate_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplate_uModBy "uModBy"
#define LANG_FT_tTemplate_uModBy "uClient for last update"
#define LANG_FL_tTemplate_uModDate "uModDate"
#define LANG_FT_tTemplate_uModDate "Unix seconds date last update"
//tTemplateSet
#define LANG_FL_tTemplateSet_uTemplateSet "uTemplateSet"
#define LANG_FT_tTemplateSet_uTemplateSet "Primary Key"
#define LANG_FL_tTemplateSet_cLabel "cLabel"
#define LANG_FT_tTemplateSet_cLabel "Short label"
#define LANG_FL_tTemplateSet_uOwner "uOwner"
#define LANG_FT_tTemplateSet_uOwner "Record owner"
#define LANG_FL_tTemplateSet_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateSet_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateSet_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateSet_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateSet_uModBy "uModBy"
#define LANG_FT_tTemplateSet_uModBy "uClient for last update"
#define LANG_FL_tTemplateSet_uModDate "uModDate"
#define LANG_FT_tTemplateSet_uModDate "Unix seconds date last update"
//tTemplateType
#define LANG_FL_tTemplateType_uTemplateType "uTemplateType"
#define LANG_FT_tTemplateType_uTemplateType "Primary Key"
#define LANG_FL_tTemplateType_cLabel "cLabel"
#define LANG_FT_tTemplateType_cLabel "Short label"
#define LANG_FL_tTemplateType_uOwner "uOwner"
#define LANG_FT_tTemplateType_uOwner "Record owner"
#define LANG_FL_tTemplateType_uCreatedBy "uCreatedBy"
#define LANG_FT_tTemplateType_uCreatedBy "uClient for last insert"
#define LANG_FL_tTemplateType_uCreatedDate "uCreatedDate"
#define LANG_FT_tTemplateType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tTemplateType_uModBy "uModBy"
#define LANG_FT_tTemplateType_uModBy "uClient for last update"
#define LANG_FL_tTemplateType_uModDate "uModDate"
#define LANG_FT_tTemplateType_uModDate "Unix seconds date last update"
//tLog
#define LANG_FL_tLog_uLog "uLog"
#define LANG_FT_tLog_uLog "Primary Key"
#define LANG_FL_tLog_cLabel "cLabel"
#define LANG_FT_tLog_cLabel "Short label"
#define LANG_FL_tLog_uLogType "uLogType"
#define LANG_FT_tLog_uLogType "Log Type"
#define LANG_FL_tLog_cHash "cHash"
#define LANG_FT_tLog_cHash "Security hash to complicate tampering"
#define LANG_FL_tLog_uPermLevel "uPermLevel"
#define LANG_FT_tLog_uPermLevel "User Perm Level"
#define LANG_FL_tLog_uLoginClient "uLoginClient"
#define LANG_FT_tLog_uLoginClient "Client Number"
#define LANG_FL_tLog_cLogin "cLogin"
#define LANG_FT_tLog_cLogin "Login name"
#define LANG_FL_tLog_cHost "cHost"
#define LANG_FT_tLog_cHost "Ip Address"
#define LANG_FL_tLog_uTablePK "uTablePK"
#define LANG_FT_tLog_uTablePK "Primar Key of the Table"
#define LANG_FL_tLog_cTableName "cTableName"
#define LANG_FT_tLog_cTableName "Name of the Table"
#define LANG_FL_tLog_cMessage "cMessage"
#define LANG_FT_tLog_cMessage "Message text"
#define LANG_FL_tLog_cServer "cServer"
#define LANG_FT_tLog_cServer "Server name"
#define LANG_FL_tLog_uOwner "uOwner"
#define LANG_FT_tLog_uOwner "Record owner"
#define LANG_FL_tLog_uCreatedBy "uCreatedBy"
#define LANG_FT_tLog_uCreatedBy "uClient for last insert"
#define LANG_FL_tLog_uCreatedDate "uCreatedDate"
#define LANG_FT_tLog_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLog_uModBy "uModBy"
#define LANG_FT_tLog_uModBy "uClient for last update"
#define LANG_FL_tLog_uModDate "uModDate"
#define LANG_FT_tLog_uModDate "Unix seconds date last update"
//tLogType
#define LANG_FL_tLogType_uLogType "uLogType"
#define LANG_FT_tLogType_uLogType "Primary Key"
#define LANG_FL_tLogType_cLabel "cLabel"
#define LANG_FT_tLogType_cLabel "Short label"
#define LANG_FL_tLogType_uOwner "uOwner"
#define LANG_FT_tLogType_uOwner "Record owner"
#define LANG_FL_tLogType_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogType_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogType_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogType_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogType_uModBy "uModBy"
#define LANG_FT_tLogType_uModBy "uClient for last update"
#define LANG_FL_tLogType_uModDate "uModDate"
#define LANG_FT_tLogType_uModDate "Unix seconds date last update"
//tBlock
#define LANG_FL_tBlock_uBlock "uBlock"
#define LANG_FT_tBlock_uBlock "Primary Key"
#define LANG_FL_tBlock_cLabel "cLabel"
#define LANG_FT_tBlock_cLabel "Short label"
#define LANG_FL_tBlock_cComment "cComment"
#define LANG_FT_tBlock_cComment "Short comment about this block"
#define LANG_FL_tBlock_uOwner "uOwner"
#define LANG_FT_tBlock_uOwner "Record owner"
#define LANG_FL_tBlock_uCreatedBy "uCreatedBy"
#define LANG_FT_tBlock_uCreatedBy "uClient for last insert"
#define LANG_FL_tBlock_uCreatedDate "uCreatedDate"
#define LANG_FT_tBlock_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tBlock_uModBy "uModBy"
#define LANG_FT_tBlock_uModBy "uClient for last update"
#define LANG_FL_tBlock_uModDate "uModDate"
#define LANG_FT_tBlock_uModDate "Unix seconds date last update"
//tView
#define LANG_FL_tView_uView "uView"
#define LANG_FT_tView_uView "Primary Key"
#define LANG_FL_tView_cLabel "cLabel"
#define LANG_FT_tView_cLabel "Short label"
#define LANG_FL_tView_uOrder "uOrder"
#define LANG_FT_tView_uOrder "Order in zone file"
#define LANG_FL_tView_uNSSet "uNSSet"
#define LANG_FT_tView_uNSSet "Name Server Set"
#define LANG_FL_tView_cMaster "cMaster"
#define LANG_FT_tView_cMaster "BIND configuration master.zones view section header"
#define LANG_FL_tView_cSlave "cSlave"
#define LANG_FT_tView_cSlave "Bind configuration slave.zones view section header"
#define LANG_FL_tView_uOwner "uOwner"
#define LANG_FT_tView_uOwner "Record owner"
#define LANG_FL_tView_uCreatedBy "uCreatedBy"
#define LANG_FT_tView_uCreatedBy "uClient for last insert"
#define LANG_FL_tView_uCreatedDate "uCreatedDate"
#define LANG_FT_tView_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tView_uModBy "uModBy"
#define LANG_FT_tView_uModBy "uClient for last update"
#define LANG_FL_tView_uModDate "uModDate"
#define LANG_FT_tView_uModDate "Unix seconds date last update"
//tRegistrar
#define LANG_FL_tRegistrar_uRegistrar "uRegistrar"
#define LANG_FT_tRegistrar_uRegistrar "Primary Key"
#define LANG_FL_tRegistrar_cLabel "cLabel"
#define LANG_FT_tRegistrar_cLabel "Registrar of Record"
#define LANG_FL_tRegistrar_uOwner "uOwner"
#define LANG_FT_tRegistrar_uOwner "Record owner"
#define LANG_FL_tRegistrar_uCreatedBy "uCreatedBy"
#define LANG_FT_tRegistrar_uCreatedBy "uClient for last insert"
#define LANG_FL_tRegistrar_uCreatedDate "uCreatedDate"
#define LANG_FT_tRegistrar_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tRegistrar_uModBy "uModBy"
#define LANG_FT_tRegistrar_uModBy "uClient for last update"
#define LANG_FL_tRegistrar_uModDate "uModDate"
#define LANG_FT_tRegistrar_uModDate "Unix seconds date last update"
//tGlossary
#define LANG_FL_tGlossary_uGlosary "uGlosary"
#define LANG_FT_tGlossary_uGlosary "Primary Key"
#define LANG_FL_tGlossary_cLabel "cLabel"
#define LANG_FT_tGlossary_cLabel "Short label"
#define LANG_FL_tGlossary_cText "cText"
#define LANG_FT_tGlossary_cText "Definition of the label referenced in cLabel"
#define LANG_FL_tGlossary_uOwner "uOwner"
#define LANG_FT_tGlossary_uOwner "Record owner"
#define LANG_FL_tGlossary_uCreatedBy "uCreatedBy"
#define LANG_FT_tGlossary_uCreatedBy "uClient for last insert"
#define LANG_FL_tGlossary_uCreatedDate "uCreatedDate"
#define LANG_FT_tGlossary_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tGlossary_uModBy "uModBy"
#define LANG_FT_tGlossary_uModBy "uClient for last update"
#define LANG_FL_tGlossary_uModDate "uModDate"
#define LANG_FT_tGlossary_uModDate "Unix seconds date last update"
//tZoneImport
#define LANG_FL_tZoneImport_uZone "uZone"
#define LANG_FT_tZoneImport_uZone "Primary Key"
#define LANG_FL_tZoneImport_uNSSet "uNSSet"
#define LANG_FT_tZoneImport_uNSSet "Group of name servers"
#define LANG_FL_tZoneImport_cZone "cZone"
#define LANG_FT_tZoneImport_cZone "Fully qualified zone name"
#define LANG_FL_tZoneImport_cHostmaster "cHostmaster"
#define LANG_FT_tZoneImport_cHostmaster "eMail address of responsible person of this zone"
#define LANG_FL_tZoneImport_uRefresh "uRefresh"
#define LANG_FT_tZoneImport_uRefresh "Slave server refresh time"
#define LANG_FL_tZoneImport_uExpire "uExpire"
#define LANG_FT_tZoneImport_uExpire "Slave server expiration time"
#define LANG_FL_tZoneImport_uSerial "uSerial"
#define LANG_FT_tZoneImport_uSerial "Zone serial number"
#define LANG_FL_tZoneImport_uZoneTTL "uZoneTTL"
#define LANG_FT_tZoneImport_uZoneTTL "Zone TTL seconds"
#define LANG_FL_tZoneImport_uRetry "uRetry"
#define LANG_FT_tZoneImport_uRetry "Slave server retry interval after uRefresh"
#define LANG_FL_tZoneImport_uTTL "uTTL"
#define LANG_FT_tZoneImport_uTTL "Default time to live of resource records"
#define LANG_FL_tZoneImport_uMailServers "uMailServers"
#define LANG_FT_tZoneImport_uMailServers "Group of mail servers"
#define LANG_FL_tZoneImport_uView "uView"
#define LANG_FT_tZoneImport_uView "Optional tView Group"
#define LANG_FL_tZoneImport_cMainAddress "cMainAddress"
#define LANG_FT_tZoneImport_cMainAddress "Main A Record"
#define LANG_FL_tZoneImport_uRegistrar "uRegistrar"
#define LANG_FT_tZoneImport_uRegistrar "Registrar of Record for this Zone if Applies"
#define LANG_FL_tZoneImport_uSecondaryOnly "uSecondaryOnly"
#define LANG_FT_tZoneImport_uSecondaryOnly "Secondary DNS Service Only. cMasterIPs Would be External Customer Provided Master"
#define LANG_FL_tZoneImport_cMasterIPs "cMasterIPs"
#define LANG_FT_tZoneImport_cMasterIPs "Slave zones master IP source(s)"
#define LANG_FL_tZoneImport_cAllowTransfer "cAllowTransfer"
#define LANG_FT_tZoneImport_cAllowTransfer "IP address(es) that are allowed to copy the zone info from the server (master or slave)"
#define LANG_FL_tZoneImport_cOptions "cOptions"
#define LANG_FT_tZoneImport_cOptions "slave.zones and master.zones zone options"
#define LANG_FL_tZoneImport_uOwner "uOwner"
#define LANG_FT_tZoneImport_uOwner "Record owner"
#define LANG_FL_tZoneImport_uCreatedBy "uCreatedBy"
#define LANG_FT_tZoneImport_uCreatedBy "uClient for last insert"
#define LANG_FL_tZoneImport_uCreatedDate "uCreatedDate"
#define LANG_FT_tZoneImport_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tZoneImport_uModBy "uModBy"
#define LANG_FT_tZoneImport_uModBy "uClient for last update"
#define LANG_FL_tZoneImport_uModDate "uModDate"
#define LANG_FT_tZoneImport_uModDate "Unix seconds date last update"
//tResourceImport
#define LANG_FL_tResourceImport_uZone "uZone"
#define LANG_FT_tResourceImport_uZone "Belongs to this tZone"
#define LANG_FL_tResourceImport_uResource "uResource"
#define LANG_FT_tResourceImport_uResource "Primary Key"
#define LANG_FL_tResourceImport_cName "cName"
#define LANG_FT_tResourceImport_cName "Resource name or @"
#define LANG_FL_tResourceImport_uTTL "uTTL"
#define LANG_FT_tResourceImport_uTTL "Resource record TTL in seconds"
#define LANG_FL_tResourceImport_uRRType "uRRType"
#define LANG_FT_tResourceImport_uRRType "Resource record type"
#define LANG_FL_tResourceImport_cParam1 "cParam1"
#define LANG_FT_tResourceImport_cParam1 "Parameter 1 of resource record"
#define LANG_FL_tResourceImport_cParam2 "cParam2"
#define LANG_FT_tResourceImport_cParam2 "Parameter 2 of resource record"
#define LANG_FL_tResourceImport_cComment "cComment"
#define LANG_FT_tResourceImport_cComment "Resource record comment"
#define LANG_FL_tResourceImport_uOwner "uOwner"
#define LANG_FT_tResourceImport_uOwner "Record owner"
#define LANG_FL_tResourceImport_uCreatedBy "uCreatedBy"
#define LANG_FT_tResourceImport_uCreatedBy "uClient for last insert"
#define LANG_FL_tResourceImport_uCreatedDate "uCreatedDate"
#define LANG_FT_tResourceImport_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tResourceImport_uModBy "uModBy"
#define LANG_FT_tResourceImport_uModBy "uClient for last update"
#define LANG_FL_tResourceImport_uModDate "uModDate"
#define LANG_FT_tResourceImport_uModDate "Unix seconds date last update"
//tMonthHit
#define LANG_FL_tMonthHit_uMonth "uMonth"
#define LANG_FT_tMonthHit_uMonth "Primary Key"
#define LANG_FL_tMonthHit_cLabel "cLabel"
#define LANG_FT_tMonthHit_cLabel "Name of Archive Table Ex. tNov2009"
#define LANG_FL_tMonthHit_uOwner "uOwner"
#define LANG_FT_tMonthHit_uOwner "Record owner"
#define LANG_FL_tMonthHit_uCreatedBy "uCreatedBy"
#define LANG_FT_tMonthHit_uCreatedBy "uClient for last insert"
#define LANG_FL_tMonthHit_uCreatedDate "uCreatedDate"
#define LANG_FT_tMonthHit_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tMonthHit_uModBy "uModBy"
#define LANG_FT_tMonthHit_uModBy "uClient for last update"
#define LANG_FL_tMonthHit_uModDate "uModDate"
#define LANG_FT_tMonthHit_uModDate "Unix seconds date last update"
//tLogMonth
#define LANG_FL_tLogMonth_uLog "uLog"
#define LANG_FT_tLogMonth_uLog "Primary Key"
#define LANG_FL_tLogMonth_cLabel "cLabel"
#define LANG_FT_tLogMonth_cLabel "Short label"
#define LANG_FL_tLogMonth_uLogType "uLogType"
#define LANG_FT_tLogMonth_uLogType "Log Type"
#define LANG_FL_tLogMonth_cHash "cHash"
#define LANG_FT_tLogMonth_cHash "Security hash to complicate tampering"
#define LANG_FL_tLogMonth_uPermLevel "uPermLevel"
#define LANG_FT_tLogMonth_uPermLevel "User Perm Level"
#define LANG_FL_tLogMonth_cLogin "cLogin"
#define LANG_FT_tLogMonth_cLogin "Login name"
#define LANG_FL_tLogMonth_uLoginClient "uLoginClient"
#define LANG_FT_tLogMonth_uLoginClient "Client Number"
#define LANG_FL_tLogMonth_cHost "cHost"
#define LANG_FT_tLogMonth_cHost "Ip Address"
#define LANG_FL_tLogMonth_uTablePK "uTablePK"
#define LANG_FT_tLogMonth_uTablePK "Primar Key of the Table"
#define LANG_FL_tLogMonth_cTableName "cTableName"
#define LANG_FT_tLogMonth_cTableName "Name of the Table"
#define LANG_FL_tLogMonth_uOwner "uOwner"
#define LANG_FT_tLogMonth_uOwner "Record owner"
#define LANG_FL_tLogMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tLogMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tLogMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tLogMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tLogMonth_uModBy "uModBy"
#define LANG_FT_tLogMonth_uModBy "uClient for last update"
#define LANG_FL_tLogMonth_uModDate "uModDate"
#define LANG_FT_tLogMonth_uModDate "Unix seconds date last update"
//tHit
#define LANG_FL_tHit_uHit "uHit"
#define LANG_FT_tHit_uHit "Primary Key"
#define LANG_FL_tHit_cZone "cZone"
#define LANG_FT_tHit_cZone "Zone name"
#define LANG_FL_tHit_uHitCount "uHitCount"
#define LANG_FT_tHit_uHitCount "Hit Counter"
#define LANG_FL_tHit_uOwner "uOwner"
#define LANG_FT_tHit_uOwner "Record owner"
#define LANG_FL_tHit_uCreatedBy "uCreatedBy"
#define LANG_FT_tHit_uCreatedBy "uClient for last insert"
#define LANG_FL_tHit_uCreatedDate "uCreatedDate"
#define LANG_FT_tHit_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tHit_uModBy "uModBy"
#define LANG_FT_tHit_uModBy "uClient for last update"
#define LANG_FL_tHit_uModDate "uModDate"
#define LANG_FT_tHit_uModDate "Unix seconds date last update"
//tHitMonth
#define LANG_FL_tHitMonth_uHit "uHit"
#define LANG_FT_tHitMonth_uHit "Primary Key"
#define LANG_FL_tHitMonth_cZone "cZone"
#define LANG_FT_tHitMonth_cZone "Zone name"
#define LANG_FL_tHitMonth_uHitCount "uHitCount"
#define LANG_FT_tHitMonth_uHitCount "Hit Counter"
#define LANG_FL_tHitMonth_uOwner "uOwner"
#define LANG_FT_tHitMonth_uOwner "Record owner"
#define LANG_FL_tHitMonth_uCreatedBy "uCreatedBy"
#define LANG_FT_tHitMonth_uCreatedBy "uClient for last insert"
#define LANG_FL_tHitMonth_uCreatedDate "uCreatedDate"
#define LANG_FT_tHitMonth_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tHitMonth_uModBy "uModBy"
#define LANG_FT_tHitMonth_uModBy "uClient for last update"
#define LANG_FL_tHitMonth_uModDate "uModDate"
#define LANG_FT_tHitMonth_uModDate "Unix seconds date last update"
//tDeletedZone
#define LANG_FL_tDeletedZone_uDeletedZone "uDeletedZone"
#define LANG_FT_tDeletedZone_uDeletedZone "Primary Key"
#define LANG_FL_tDeletedZone_cZone "cZone"
#define LANG_FT_tDeletedZone_cZone "Fully qualified zone name"
#define LANG_FL_tDeletedZone_uNSSet "uNSSet"
#define LANG_FT_tDeletedZone_uNSSet "Group of name servers"
#define LANG_FL_tDeletedZone_cHostmaster "cHostmaster"
#define LANG_FT_tDeletedZone_cHostmaster "eMail address of responsible person of this zone"
#define LANG_FL_tDeletedZone_uSerial "uSerial"
#define LANG_FT_tDeletedZone_uSerial "Zone serial number"
#define LANG_FL_tDeletedZone_uExpire "uExpire"
#define LANG_FT_tDeletedZone_uExpire "Slave server expiration time"
#define LANG_FL_tDeletedZone_uRefresh "uRefresh"
#define LANG_FT_tDeletedZone_uRefresh "Slave server refresh time"
#define LANG_FL_tDeletedZone_uTTL "uTTL"
#define LANG_FT_tDeletedZone_uTTL "Default time to live of resource records"
#define LANG_FL_tDeletedZone_uRetry "uRetry"
#define LANG_FT_tDeletedZone_uRetry "Slave server retry interval after uRefresh"
#define LANG_FL_tDeletedZone_uZoneTTL "uZoneTTL"
#define LANG_FT_tDeletedZone_uZoneTTL "Zone TTL seconds"
#define LANG_FL_tDeletedZone_uMailServers "uMailServers"
#define LANG_FT_tDeletedZone_uMailServers "Group of mail servers"
#define LANG_FL_tDeletedZone_uView "uView"
#define LANG_FT_tDeletedZone_uView "Optional tView Group"
#define LANG_FL_tDeletedZone_cMainAddress "cMainAddress"
#define LANG_FT_tDeletedZone_cMainAddress "Main A Record"
#define LANG_FL_tDeletedZone_uRegistrar "uRegistrar"
#define LANG_FT_tDeletedZone_uRegistrar "Registrar of Record for this Zone if Applies"
#define LANG_FL_tDeletedZone_uSecondaryOnly "uSecondaryOnly"
#define LANG_FT_tDeletedZone_uSecondaryOnly "Secondary DNS Service Only. cMasterIPs Would be External Customer Provided Master"
#define LANG_FL_tDeletedZone_cMasterIPs "cMasterIPs"
#define LANG_FT_tDeletedZone_cMasterIPs "Slave zones master IP source(s)"
#define LANG_FL_tDeletedZone_cAllowTransfer "cAllowTransfer"
#define LANG_FT_tDeletedZone_cAllowTransfer "IP address(es) that are allowed to copy the zone info from the server (master or slave)"
#define LANG_FL_tDeletedZone_cOptions "cOptions"
#define LANG_FT_tDeletedZone_cOptions "slave.zones and master.zones zone options"
#define LANG_FL_tDeletedZone_uOwner "uOwner"
#define LANG_FT_tDeletedZone_uOwner "Record owner"
#define LANG_FL_tDeletedZone_uCreatedBy "uCreatedBy"
#define LANG_FT_tDeletedZone_uCreatedBy "uClient for last insert"
#define LANG_FL_tDeletedZone_uCreatedDate "uCreatedDate"
#define LANG_FT_tDeletedZone_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tDeletedZone_uModBy "uModBy"
#define LANG_FT_tDeletedZone_uModBy "uClient for last update"
#define LANG_FL_tDeletedZone_uModDate "uModDate"
#define LANG_FT_tDeletedZone_uModDate "Unix seconds date last update"
//tDeletedResource
#define LANG_FL_tDeletedResource_uDeletedResource "uDeletedResource"
#define LANG_FT_tDeletedResource_uDeletedResource "Primary Key"
#define LANG_FL_tDeletedResource_uZone "uZone"
#define LANG_FT_tDeletedResource_uZone "Belongs to this tZone"
#define LANG_FL_tDeletedResource_cName "cName"
#define LANG_FT_tDeletedResource_cName "Resource name or @"
#define LANG_FL_tDeletedResource_uTTL "uTTL"
#define LANG_FT_tDeletedResource_uTTL "Resource record TTL in seconds"
#define LANG_FL_tDeletedResource_uRRType "uRRType"
#define LANG_FT_tDeletedResource_uRRType "Resource record type"
#define LANG_FL_tDeletedResource_cParam1 "cParam1"
#define LANG_FT_tDeletedResource_cParam1 "Parameter 1 of resource record"
#define LANG_FL_tDeletedResource_cParam2 "cParam2"
#define LANG_FT_tDeletedResource_cParam2 "Parameter 2 of resource record"
#define LANG_FL_tDeletedResource_cComment "cComment"
#define LANG_FT_tDeletedResource_cComment "Resource record comment"
#define LANG_FL_tDeletedResource_uOwner "uOwner"
#define LANG_FT_tDeletedResource_uOwner "Record owner"
#define LANG_FL_tDeletedResource_uCreatedBy "uCreatedBy"
#define LANG_FT_tDeletedResource_uCreatedBy "uClient for last insert"
#define LANG_FL_tDeletedResource_uCreatedDate "uCreatedDate"
#define LANG_FT_tDeletedResource_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tDeletedResource_uModBy "uModBy"
#define LANG_FT_tDeletedResource_uModBy "uClient for last update"
#define LANG_FL_tDeletedResource_uModDate "uModDate"
#define LANG_FT_tDeletedResource_uModDate "Unix seconds date last update"
//tClient
#define LANG_FL_tClient_uClient "uClient"
#define LANG_FT_tClient_uClient "Primary Key"
#define LANG_FL_tClient_cLabel "cLabel"
#define LANG_FT_tClient_cLabel "Short label"
#define LANG_FL_tClient_cInfo "cInfo"
#define LANG_FT_tClient_cInfo "Unformatted info/address etc."
#define LANG_FL_tClient_cEmail "cEmail"
#define LANG_FT_tClient_cEmail "Main Email"
#define LANG_FL_tClient_cCode "cCode"
#define LANG_FT_tClient_cCode "Enterprise wide customer/contact tracking"
#define LANG_FL_tClient_uOwner "uOwner"
#define LANG_FT_tClient_uOwner "Record owner"
#define LANG_FL_tClient_uCreatedBy "uCreatedBy"
#define LANG_FT_tClient_uCreatedBy "uClient for last insert"
#define LANG_FL_tClient_uCreatedDate "uCreatedDate"
#define LANG_FT_tClient_uCreatedDate "Unix seconds date last insert"
#define LANG_FL_tClient_uModBy "uModBy"
#define LANG_FT_tClient_uModBy "uClient for last update"
#define LANG_FL_tClient_uModDate "uModDate"
#define LANG_FT_tClient_uModDate "Unix seconds date last update"
